apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kartify-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/edikkan/kartify.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kartify-components
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: kartify
            url: https://kubernetes.default.svc
            components: backend
          - cluster: kartify
            url: https://kubernetes.default.svc
            components: frontend
          - cluster: kartify
            url: https://kubernetes.default.svc
            components: database
          - cluster: kartify
            url: https://kubernetes.default.svc
            components: redis
  template:
    metadata:
      name: kartify-{{components}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/edikkan/kartify.git
        targetRevision: HEAD
        path: k8s/{{components}}
      destination:
        server: '{{url}}'
        namespace: kartify
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
